### ISSUE TITLE
Add Windows 7 Support

### ISSUE THREAD

**Issue by woaidianqian** [akhilesh-balaji/Textylic#3]
The software does not support windows7，Hope this useful program can support Windows7

**Comment by akhilesh-balaji** [comment]
@woaidianqian Thanks for the idea! I had already thought about this, but decided that testing would be a pain, as I did not have a Windows 7 device. Support is already there, though. In the next release, I will simply enable the checkbox in the installer for Windows 7. However, please remember that I will not support any issues that that come up on a Windows 7 device, simply because I only have a Windows 10 device.

**Comment by woaidianqian** [comment]
https://github.com/woaidianqian/Textylic/releases/tag/win7%C3%9786
this pack supports win7 32

**Comment by akhilesh-balaji** [comment]
@woaidianqian  Sure, thanks! I'll take a look into it. You can expect complete windows 7 support by the next release in a couple of weeks.

**Comment by akhilesh-balaji** [comment]
Added support. Check out release 2.0: https://github.com/akhilesh-balaji/Textylic/releases/tag/v2.0
